In [1]:
import pandas as pd
import numpy as np
from numpy import random, array
from scipy import special
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('movielens_data_genome/movie_dataset_public_final/scores/glmer.csv')

In [3]:
df

tag  item_id     score
0                  airplane        2  0.042391
1                  airplane        3  0.050673
2                  airplane        4  0.033161
3                  airplane        5  0.047030
4                  airplane        6  0.051117
...                     ...      ...       ...
10551650  private detective    25923  0.103525
10551651  private detective    25938  0.074306
10551652  private detective    25943  0.515465
10551653  private detective    25996  0.082231
10551654  private detective    26002  0.600222

[10551655 rows x 3 columns]

In [4]:
#Jumanji (1995)
df[df.item_id == 2]

tag  item_id     score
0                  airplane        2  0.042391
9734                   aids        2  0.101941
19468               science        2  0.228367
29202           adolescence        2  0.125766
38936               mystery        2  0.062583
...                     ...      ...       ...
10502986      investigation        2  0.102354
10512720          courtroom        2  0.048113
10522454              light        2  0.354336
10532188                cgi        2  0.165919
10541922  private detective        2  0.040606

[1084 rows x 3 columns]

In [5]:
titles = df["item_id"].unique()

In [6]:
len(titles)

9734

In [7]:
master_mat = []

for movie in titles[0:500]:
    if len(df[df.item_id == movie]) != 1084:
        print(f'error {movie}')

    else:
       matrix = list(df[df.item_id == movie].score.values)
       master_mat.append(matrix)
master_mat = array(master_mat)

In [8]:
master_mat

array([[0.04239084, 0.10194136, 0.2283672 , ..., 0.35433628, 0.16591942,
        0.04060626],
       [0.05067322, 0.07821968, 0.07705283, ..., 0.26849033, 0.03877314,
        0.05475678],
       [0.033161  , 0.12362608, 0.05892531, ..., 0.33532089, 0.03626103,
        0.02334027],
       ...,
       [0.05420377, 0.14424375, 0.11918487, ..., 0.32899504, 0.05771888,
        0.02871232],
       [0.09420181, 0.38109092, 0.14401878, ..., 0.3386722 , 0.05379181,
        0.09089558],
       [0.03918486, 0.20078731, 0.02397578, ..., 0.09457408, 0.03291332,
        0.01687108]])

In [9]:
sample_user = random.choice(titles, 20)

In [10]:
sample_user

array([ 1286,  7217,    77,  2990, 57972, 52952,  3788,  6616, 96610,
       46967,  2642,  1839,  2910,  7883,  1039, 54910, 66744,   469,
        6792, 27857], dtype=int64)

In [11]:
sample_user_matrix = []
for movie in sample_user:
    if len(df[df.item_id == movie]) != 1084:
        print(f'error {movie}')

    else:
       matrix = list(df[df.item_id == movie].score.values)
       sample_user_matrix.append(matrix)

mat = array(sample_user_matrix)


In [12]:
mat

array([[0.04762648, 0.08575283, 0.4417353 , ..., 0.45039434, 0.05908123,
        0.03191696],
       [0.04097444, 0.06371431, 0.03715451, ..., 0.31411245, 0.04640873,
        0.57089158],
       [0.04564934, 0.18847167, 0.04627216, ..., 0.29244322, 0.04716999,
        0.08408927],
       ...,
       [0.03099296, 0.21537797, 0.04563826, ..., 0.18258552, 0.04084898,
        0.03095276],
       [0.13439707, 0.28783808, 0.16374878, ..., 0.6937856 , 0.07812832,
        0.03463671],
       [0.02380272, 0.32412197, 0.05906456, ..., 0.18750171, 0.02828002,
        0.01643653]])

In [13]:
matsq = mat**2

In [14]:
matsq

array([[2.26828187e-03, 7.35354764e-03, 1.95130074e-01, ...,
        2.02855064e-01, 3.49059158e-03, 1.01869258e-03],
       [1.67890453e-03, 4.05951385e-03, 1.38045798e-03, ...,
        9.86666333e-02, 2.15376984e-03, 3.25917198e-01],
       [2.08386182e-03, 3.55215704e-02, 2.14111278e-03, ...,
        8.55230374e-02, 2.22500822e-03, 7.07100498e-03],
       ...,
       [9.60563607e-04, 4.63876696e-02, 2.08285095e-03, ...,
        3.33374730e-02, 1.66863903e-03, 9.58073110e-04],
       [1.80625731e-02, 8.28507611e-02, 2.68136638e-02, ...,
        4.81338452e-01, 6.10403502e-03, 1.19970148e-03],
       [5.66569325e-04, 1.05055049e-01, 3.48862211e-03, ...,
        3.51568917e-02, 7.99759397e-04, 2.70159607e-04]])

In [15]:
rows, cols = matsq.shape

In [16]:
agg = np.average(matsq, axis = 0)

In [17]:
agg

array([0.0132424 , 0.01780052, 0.0402481 , ..., 0.11600958, 0.00449399,
       0.02882033])

In [18]:
aggroot = agg**0.5

In [19]:
aggroot

array([0.11507563, 0.13341861, 0.2006193 , ..., 0.34060179, 0.06703722,
       0.16976552])

In [20]:
base = np.average(mat, axis = 0)
base

array([0.06365182, 0.10258356, 0.11158615, ..., 0.31189881, 0.05631152,
       0.10517362])

In [21]:
aggroot

array([0.11507563, 0.13341861, 0.2006193 , ..., 0.34060179, 0.06703722,
       0.16976552])

In [22]:
aggroot

array([0.11507563, 0.13341861, 0.2006193 , ..., 0.34060179, 0.06703722,
       0.16976552])

In [23]:
rows, cols = master_mat.shape

In [24]:
dist = []
for r in range(rows):
    d = np.linalg.norm(aggroot-master_mat[r])
    dist.append(d)

In [25]:
dist

[5.3591006601560975,
 4.4315133748834485,
 4.593779796424947,
 4.94693907358487,
 5.193029168126121,
 4.762412147887116,
 5.106538699798425,
 5.237279208572628,
 5.270068537093101,
 4.81963693863736,
 5.293513181421856,
 5.689137651519572,
 4.299047146688644,
 5.296478093102855,
 5.770547496484381,
 5.419513551991006,
 4.4610956677041145,
 5.485213300252138,
 4.637029173386751,
 5.063831159004852,
 4.51433392601396,
 5.057874149525914,
 4.271946313738391,
 4.802532247853936,
 4.064933861605447,
 4.8688595997473545,
 5.1721733658757625,
 5.184639120192155,
 3.8446613205167592,
 4.669039695483594,
 6.313602755761496,
 5.197961488890914,
 5.3061248126775045,
 4.610449810750769,
 4.769990254832582,
 4.7353346391906195,
 5.856763971069049,
 5.475979764459897,
 4.5827951474307955,
 4.448376127426312,
 4.21780398897847,
 4.277792282189937,
 5.594564780869198,
 4.427576775749056,
 4.641513314069579,
 6.48384436753473,
 6.009839408908781,
 4.7977314610191675,
 7.2983353830946935,
 3.68142295278

In [26]:
dfresult = pd.DataFrame(titles[0:-1], columns = ['movie_id'])

In [27]:
dfresult['score1'] = dist

ValueError: Length of values (500) does not match length of index (9733)

In [ ]:
dfresult

movie_id    score1
0            2  4.589063
1            3  3.778091
2            4  3.932526
3            5  4.170243
4            6  5.736175
...        ...       ...
9728     25923  5.454709
9729     25938  4.972437
9730     25943  5.983937
9731     25996  4.430613
9732     26002  4.488838

[9733 rows x 2 columns]

In [ ]:
dfresult['movie_title'] = ''

In [ ]:
dfresult['score2'] = dist2

In [ ]:
dfresult = dfresult[~dfresult.movie_id.isin(sample_user)]

In [ ]:
sample_user2 = random.choice(titles, 20)

sample_user_matrix2 = []
for movie in sample_user2:
    if len(df[df.item_id == movie]) != 1084:
        print(f'error {movie}')

    else:
       matrix = list(df[df.item_id == movie].score.values)
       sample_user_matrix2.append(matrix)

mat2 = array(sample_user_matrix2)

In [ ]:
matsq2 = mat2**2
agg2 = np.average(matsq2, axis = 0)
aggroot2 = agg2**0.5

dist2 = []
for r in range(rows):
    d = np.linalg.norm(aggroot2-master_mat[r])
    dist2.append(d)

In [ ]:
dist2

[4.980456425427371,
 4.4141509962037,
 4.673300262486606,
 4.928020976574808,
 5.421527412954763,
 4.8250504760973785,
 4.948194534661785,
 5.1468834001478765,
 5.225942215116121,
 4.802429213145036,
 5.318420231447104,
 5.473517451610332,
 4.547551386275889,
 5.0491406956467335,
 6.270926995686859,
 5.4087726362602195,
 4.635820016288275,
 5.4282891624020095,
 4.564682313439829,
 5.343602799141624,
 4.739909075610671,
 5.179438755544158,
 4.222187765179589,
 5.3211834551232196,
 4.152025302495652,
 4.923558668953733,
 5.2508604990048795,
 5.444390012597587,
 4.219286835882051,
 4.71894298982115,
 6.758556047719277,
 5.100411171896026,
 5.064781143460303,
 4.913661164741237,
 5.028490758091167,
 4.683638322874247,
 5.724917802092154,
 5.465595736755251,
 4.729022029826772,
 4.552842731746559,
 4.393834707380786,
 4.372649015666484,
 5.044631942318933,
 4.770279711083614,
 4.844273583468436,
 6.872479541469859,
 5.564597186981068,
 5.174248067748104,
 7.550537173748884,
 4.0933805442325

In [ ]:
dfresult = dfresult[~dfresult.movie_id.isin(sample_user2)]

In [ ]:
dfresult['avg'] = (dfresult.score1 + dfresult.score2)/2 

C:\Users\Praveen Bandla\AppData\Local\Temp\ipykernel_13060\3848401921.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfresult['avg'] = (dfresult.score1 + dfresult.score2)/2


In [ ]:
dfresult = dfresult.sort_values(by = ['avg'], ascending = False)
dfresult

movie_id    score1 movie_title    score2       avg
2613      2959  8.755004              8.312200  8.533602
279        296  8.648537              8.345477  8.497007
976       1089  8.673972              8.317009  8.495491
2266      2571  8.714110              7.980783  8.347446
337        356  8.435524              8.216687  8.326105
...        ...       ...         ...       ...       ...
2419      2749  3.384166              3.763945  3.574056
3162      3605  3.448049              3.673717  3.560883
2437      2767  3.230638              3.824680  3.527659
2407      2736  3.253719              3.671982  3.462851
2509      2844  3.320573              3.601013  3.460793

[9693 rows x 5 columns]

In [ ]:
sample_user

array([ 3501,  7150, 41226,  7123, 85736,  5873,  4335,  2984,  7068,
         531,  5898,  3616,  6168, 53322,   239, 31408, 97024,  5126,
        6285, 54910], dtype=int64)

In [ ]:
sample_user = ["Murphy's Romance (1985)", "Stuck on You (2003)", "Sounder (1972)", 
               "Naked Lunch (1991)", "BURN-E (2008)", "The Emperor's Club (2002)",
               "Midnight Madness (1980)", "On Any Sunday (1971)", "Last Year at Marienbad", "Secret Garden, The (1993)",...]

sample_user2 = []

In [ ]:
import json
f = open('C:/Users/Praveen Bandla/Desktop/Winter 2023/PIC 16B/Project/movielens_data_genome/movie_dataset_public_final/raw/metadata.json')

In [ ]:
sample_user2

array([ 8257, 25904, 79274,  2283,   397,  6790,  2663, 89305,  7847,
       71450, 87232,  4950,  4567, 93855, 60735,  1877,  6311, 26294,
       25835, 33880], dtype=int64)