In [5]:
import pandas as pd
import numpy as np

In [4]:
#file with all label values for each movie
df = pd.read_csv('movielens_data_genome/movie_dataset_public_final/scores/glmer.csv')
#currently only has 9734 movies
titles = df['item_id'].unique()

In [38]:
df

tag  item_id     score
0                  airplane        2  0.042391
1                  airplane        3  0.050673
2                  airplane        4  0.033161
3                  airplane        5  0.047030
4                  airplane        6  0.051117
...                     ...      ...       ...
10551650  private detective    25923  0.103525
10551651  private detective    25938  0.074306
10551652  private detective    25943  0.515465
10551653  private detective    25996  0.082231
10551654  private detective    26002  0.600222

[10551655 rows x 3 columns]

In [6]:
#generating user watch history based on random for now. Need to add actual history later
sample_user = np.random.choice(titles, 20)

In [7]:
sample_user

array([ 7669,  1519,  6334,  3733,   653,  3385, 46970,  2528,  2112,
        4937,  7040,  3323,   543,  7206,   539,  5141,  2976,  3448,
       26776,  2227], dtype=int64)

In [10]:
# creating a matrix where (in order of the titles in sample_user) each row corresponds to the tag values of the given movie title

sample_user_matrix = []

for movie in sample_user:
    #skip if for some reason the movie does not contain all labels
    if len(df[df.item_id == movie]) != 1084:
        print(f'error {movie}')
    
    #if the movie contains all label values, obtain the tag vector from the main df
    else:
        matrix = list(df[df.item_id == movie].score.values)
        sample_user_matrix.append(matrix)

#turning the list of lists into a matrix as a 2D array
mat = np.array(sample_user_matrix)

In [11]:
mat

array([[0.01309072, 0.03855601, 0.04120019, ..., 0.37809796, 0.07247777,
        0.03176257],
       [0.02902799, 0.17330693, 0.04312127, ..., 0.45028362, 0.05209942,
        0.03157887],
       [0.0171652 , 0.05456459, 0.04096343, ..., 0.43985189, 0.04781196,
        0.0630331 ],
       ...,
       [0.11358721, 0.10777494, 0.10856156, ..., 0.39445542, 0.05571239,
        0.04677516],
       [0.63689595, 0.08807254, 0.02966368, ..., 0.45814144, 0.04726947,
        0.11036657],
       [0.02840555, 0.03726016, 0.01860107, ..., 0.27293054, 0.04593019,
        0.25398927]])

In [12]:
matsq = mat**2
agg = np.average(matsq, axis = 0)
aggroot = agg**0.5

In [13]:
master_mat = []

for movie in titles:
    if len(df[df.item_id == movie]) != 1084:
        print(f'error {movie}')

    else:
       matrix = list(df[df.item_id == movie].score.values)
       master_mat.append(matrix)
master_mat = np.array(master_mat)

error 1


In [14]:
rows, cols = master_mat.shape
dist = []
for r in range(rows):
    d = np.linalg.norm(aggroot-master_mat[r])
    dist.append(d)

In [15]:
dist

[5.002995795344114,
 4.0184385201567006,
 4.2719097203248495,
 4.452609101352589,
 5.230199883020098,
 4.30532612163956,
 4.8479420050478055,
 5.2653133038921,
 5.549176974289666,
 4.366843253554717,
 5.229380277442762,
 5.344534484672119,
 4.428280906090171,
 5.227114907866211,
 5.99641861104943,
 4.767162344256778,
 4.374691144910162,
 5.187077908270639,
 4.528422233381626,
 4.8827919818681575,
 4.58590533100148,
 5.300748672500721,
 4.126426325047133,
 4.934752348651792,
 3.8272489626618706,
 4.545834269066809,
 4.807579865000013,
 5.454087754812237,
 4.1005924955988275,
 4.284343812592436,
 6.553401461525147,
 4.966554623485289,
 4.712936712593988,
 4.6301076510915875,
 4.653455177449159,
 4.469696140477717,
 5.374481344327943,
 4.821319021102193,
 4.560476913728456,
 4.365714491556697,
 4.219729762162415,
 4.053750716107736,
 5.609880073029398,
 4.442167855709487,
 4.3632796941270096,
 6.894177871124228,
 5.408259882673013,
 4.934769735696178,
 7.294122893591394,
 3.58323753732277

In [16]:
master_mat

array([[0.04239084, 0.10194136, 0.2283672 , ..., 0.35433628, 0.16591942,
        0.04060626],
       [0.05067322, 0.07821968, 0.07705283, ..., 0.26849033, 0.03877314,
        0.05475678],
       [0.033161  , 0.12362608, 0.05892531, ..., 0.33532089, 0.03626103,
        0.02334027],
       ...,
       [0.09837806, 0.09443736, 0.06874861, ..., 0.28673736, 0.05932984,
        0.51546525],
       [0.06705404, 0.0616011 , 0.03220481, ..., 0.21616918, 0.0455074 ,
        0.08223121],
       [0.01848705, 0.0723112 , 0.01997355, ..., 0.10833663, 0.03687084,
        0.60022248]])

In [18]:
dfresult = pd.DataFrame(titles[0:-1], columns = ['movie_id'])

In [19]:
dfresult['score1'] = dist

In [22]:
dfresult = dfresult.sort_values(by = ['score1'], ascending = False)
dfresult

movie_id    score1
2266      2571  8.290565
1058      1196  8.286955
279        296  8.179588
2613      2959  8.164415
244        260  8.154411
...        ...       ...
4905      5646  3.362707
3380      3852  3.342245
2407      2736  3.266341
7195     30898  3.246104
820        921  3.180322

[9733 rows x 2 columns]

In [31]:
dfrecommend = dfresult[0:20]

In [24]:
import json

lines = []
for line in open('movielens_data_genome\\movie_dataset_public_final\\raw\\metadata_updated.json', 'r'):
    lines.append(json.loads(line))

In [35]:
for line in lines:
    if line['item_id'] in dfrecommend.movie_id:
        print(line['title'])

Gumby: The Movie (1995)
My Family (1995)
Picture Bride (Bijo photo) (1994)
What's Eating Gilbert Grape (1993)
Mrs. Doubtfire (1993)
Farewell to Arms, A (1932)
Bitter Sugar (Azúcar amarga) (1996)
Swingers (1996)
For the Moment (1994)
Christmas Carol, A (1938)
Blank Check (1994)
Butcher's Wife, The (1991)
Night of the Comet (1984)
Burglar (1987)
Summer Rental (1985)
Vertical Ray of the Sun, The (Mua he chieu thang dung) (2000)
Black Like Me (1964)
Inquisitor, The (a.k.a. Under Suspicion) (Garde à vue) (1981)


In [40]:
for line in lines:
    if line['item_id'] in sample_user:
        print(line['title'])

Sleepless in Seattle (1993)
So I Married an Axe Murderer (1993)
Dragonheart (1996)
Broken English (1996)
Grand Canyon (1991)
Lodger: A Story of the London Fog, The (1927)
Logan's Run (1976)
Bringing Out the Dead (1999)
Chain of Fools (2000)
Volunteers (1985)
Good Morning, Vietnam (1987)
Paper Chase, The (1973)
Fatso (1980)
Bad News Bears in Breaking Training, The (1977)
Blue Car (2002)
To Live and Die in L.A. (1985)
Mon Oncle (My Uncle) (1958)
Pride and Prejudice (1995)
Porco Rosso (Crimson Pig) (Kurenai no buta) (1992)
Talladega Nights: The Ballad of Ricky Bobby (2006)


In [43]:
lines[1]

{'title': 'Jumanji (1995)',
 'directedBy': 'Joe Johnston',
 'starring': 'Jonathan Hyde, Bradley Pierce, Robin Williams, Kirsten Dunst',
 'avgRating': 3.26605,
 'imdbId': '0113497',
 'item_id': 2}

In [49]:
df.tag.unique()

array(['airplane', 'aids', 'science', ..., 'light', 'cgi',
       'private detective'], dtype=object)

In [47]:
df[df.item_id == 1].tag

9733                     aids
19467                 science
29201             adolescence
38935                 mystery
48669                 western
                  ...        
10502985        investigation
10512719            courtroom
10522453                light
10532187                  cgi
10541921    private detective
Name: tag, Length: 1083, dtype: object